### ISSUE TITLE
configuration test failed

### ISSUE THREAD

**Issue by azmeuk** [python-ldap/python-slapd#1]
On some devices, the `README` examples raises an exception:

```python
>>> import slapd
>>> process = slapd.Slapd()
>>> process.start()
2021-04-02 15:52:38,587 ERROR 606721a6 ldif_read_file: Permission denied for ".../python-ldap-test-34321/slapd.d/cn=config.ldif"
slaptest: bad configuration directory!

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../env/lib/python3.8/site-packages/slapd/__init__.py", line 389, in start
    self._test_config()
  File ".../env/lib/python3.8/site-packages/slapd/__init__.py", line 335, in _test_config
    raise RuntimeError("configuration test failed")
RuntimeError: configuration test failed

configuration test failed
```
```
$ ./env/bin/python --version
Python 3.8.5

$ slapd -V
@(#) $OpenLDAP: slapd  (Ubuntu) (Feb 18 2021 14:22:15) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by azmeuk** [comment]
Fixed by 379c7f5
